### ISSUE TITLE
getGroup

### ISSUE THREAD

**Issue by xiao0320** [ratezpro/yeslinepy#3]
I used your api and he reflected the error
error code:API method not capable: 'getGroup'

**Comment by ratezpro** [comment]
LINE has discontinued the use of getGroup and switched to using getChats

**Comment by xiao0320** [comment]
I changed getgroup to getChats but it shows
Error code: 'GetChatsResponse' object has no attribute 'name'

**Comment by xiao0320** [comment]
I am using the file generated by the old version of linepy and replaced it with your new version of linepy,
